	
	
	
	
	 # questions Vocabs....13 part---
	

questions=  (   "Vocabs Quiz will start in 30 secs",
											
					"841. Accommodative (Adj.) ",
					"842. Appetite (noun) ",
					"843. Devolution (noun) ",
					"844. Assiduously (adverb) ",
					"845. Foray (noun) ",
					"846. Fiasco (noun) ",
					"847. Muddle (verb) ",
					"848. Spate (noun) ",
					"849. Inclusivity (noun) ",
					"850. Incumbent (adj) ",
					"851. Sui generis (adj) ",
					"852. Credence (noun) ",
					"853. Apocalypse (noun) ",
					"854. Contour (noun) ",
					"855. Quinolone (noun) ",
					"856. Formidable (adj) ",
					"857. Unprecedented (adj) ",
					"858. Dearth (noun) ",
					"859. Drudgery (noun) ",
					"860. Vend (verb) ",
					"861. Quest (noun) ",
					"862. Elude (verb) ",
					"863. Insurgency (noun) ",
					"864. Envoy (noun) ",
					"865. Litany (noun) ",
					"866. Rebut (verb) ",
					"867. Clout (noun) ",
					"868. Direness (noun) ",
					"869. Unviable (adj) ",
					"870. Hegemony (noun) ",
					"871. Communique (noun) ",
					"872. Bonhomie (noun) ",
					"873. In tandem (ph) ",
					"874. Tepid (adj) ",
					"875. Succour (noun) ",
					"876. Egregious (adj) ",
					"877. Rampant (adj) ",
					"878. Coinage (noun) ",
					"879. Ethos (noun) ",
					"880. Mutate (verb) ",
					"881. Progeny (noun) ",
					"882. Lax (adj) ",
					"883. Proliferation (noun) ",
					"884. Lumpen (adj) ",
					"885. Battered (adj) ",
					"886. Diligence (noun) ",
					"887. Probe (noun/verb) ",
					"888. Moratorium (noun) ",
					"889. Conscience (noun) ",
					"890. Ab initio (adv) ",
					"891. Facet (noun) ",
					"892. Unsolicited (adj) ",
					"893. Malaise (noun) ",
					"894. Corroborate (verb) ",
					"895. Redemption (noun) ",
					"896. Accomplice (noun) ",
					"897. Concoct (verb) ",
					"898. Rhetoric (noun) ",
					"899. Appeasement (noun) ",
					"900. Lynching (verb) ",
					"901. Contemporary (adj) ",
					"902. Perpetrator (noun) ",
					"903. Inextricably (adv) ",
					"904. Benevolence (noun) ",
					"905. Contemptuously (adv) ",
					"906. Adjudicate (verb) ",
					"907. Reprieve (verb) ",
					"908. Waiver (noun) ",
					"909. Deleterious (adj) ",
					"910. Deem (verb) ",
					"911. Discontent (noun) ",
					"912. Endorse (verb) ",
					"913. Multifaceted (adj) ",
					"914. Nuisance (noun) ",
					"915. Elusive (adj) ",
					"916. Rapacious (adj) ",
					"917. Devastation (noun) ",
					"918. Endow (verb) ",
					"919. Dire (adj) ",
					"920. Scathing (adj) ",

                    "Now Over "
					)
					
					
					
#//Answers  //   Vocabs pt 13  part---
	



 
sol = (  " Be Ready",
					"841.Ans:  = Willing to fit in with someone's wishes or needs.  ",
					"842.Ans:  = A natural desire to satisfy a bodily need, especially for food. ",
					"843.Ans:  = The transfer or delegation of power to a lower level,especially by central government to local or regionaladministration. ",
					"844.Ans:  = With great care and perseverance.   ",
					"845.Ans:  = A sudden attack or incursion into enemy territory, especiallyto obtain something   ",
					"846.Ans:  = A complete failure, especially a ludicrous or humiliatingone ",
					"847.Ans:  = Bring into a disordered or confusing state  ",
					"848.Ans:  = A large number of similar things coming in quick succession",
					"849.Ans:  = The practice or policy of including people who mightotherwise be excluded or marginalized",
					"850.Ans:  = the person or group that currently has the title or position  ",
					"851.Ans:  = Unique",
					"852.Ans:  = Belief in or acceptance of something as true",
					"853.Ans:  = The complete final destruction of the world, as described inthe biblical book of revelation ",
					"854.Ans:  = An outline representing or bounding the shape or form ofsomething -  ",
					"855.Ans:  = An antibiotic derived from quinoline and used chiefly againstgram-negative organisms",
					"856.Ans:  = Inspiring fear or respect through being impressively large,powerful, intense, or capable ",
					"857.Ans:  = Never done or known before  ",
					"858.Ans:  = A scarcity or lack of something",
					"859.Ans:  = Hard menial or dull work ",
					"860.Ans:  = Offer (small items) for sale, either from a stall or from a slotmachine",
					"861.Ans:  = A long or arduous search for something  ",
					"862.Ans:  = Escape from or avoid (a danger, enemy, or pursuer)  ",
					"863.Ans:  = An active revolt or uprising   ",
					"864.Ans:  = A messenger or representative, especially one on adiplomatic mission, ambassador -",
					"865.Ans:  = A series of prayer, petition, invocation",
					"866.Ans:  = Claim or prove that (evidence or an accusation) is false ",
					"868.Ans:  = Urgent desperate",
					"869.Ans:  = Not capable of working successfully not feasible  ",
					"870.Ans:  = Leadership or dominance, especially by one state or socialgroup over others   ",
					"871.Ans:  = An official announcement or statement, especially one madeto the media  ",
					"872.Ans:  = Cheerful friendliness geniality",
					"873.Ans:  = One behind another",
					"874.Ans:  = Showing little enthusiasm",
					"875.Ans:  = Assistance and support in times of hardship and distress  ",
					"876.Ans:  = Outstandingly bad shocking  ",
					"877.Ans:  = Uncontrolled, unchecked ",
					"878.Ans:  = The invention of a new word or phrase, coins collectively",
					"879.Ans:  = The characteristic spirit of a culture, era, or community  ",
					"880.Ans:  = Change in form or nature ",
					"881.Ans:  = A descendant or the descendants of a person ",
					"882.Ans:  = Not sufficiently strict, severe, or careful   ",
					"883.Ans:  = Rapid increase in the number or amount of something ",
					"884.Ans:  = Uninterested in revolutionary advancement",
					"885.Ans:  = Injured by repeated blows or punishment   ",
					"886.Ans:  = Careful and persistent work or effort",
					"887.Ans:  = Investigation, inquiry  ",
					"888.Ans:  = A temporary prohibition of an activity",
					"889.Ans:  = A person's moral sense of right and wrong ",
					"890.Ans:  = From the beginning  ",
					"891.Ans:  = A particular aspect or feature of something  ",
					"892.Ans:  = Not asked for given or done voluntarily   ",
					"893.Ans:  = Unhappiness, restlessness  ",
					"894.Ans:  = Confirm or give support to",
					"895.Ans:  = The action of saving or being saved from sin, error, or evil  ",
					"896.Ans:  = A person who helps another commit a crime- ",
					"897.Ans:  = Create or devise (a story or plan) ",
					"898.Ans:  = The art of effective or persuasive speaking or writing,expression",
					"899.Ans:  = Satisfaction, gratify   ",
					"900.Ans:  = (of a group of people) kill (someone) for an alleged offencewithout a legal trial",
					"901.Ans:  = Living or occurring at the same time",
					"902.Ans:  = A person who carries out a harmful, illegal, or immoral act  ",
					"903.Ans:  = In a way that is impossible to disentangle or separate  ",
					"904.Ans:  = The quality of being well meaning kindness   ",
					"905.Ans:  = In a scornful way that shows disdain",
					"906.Ans:  = Make a formal judgement on a disputed matter ",
					"907.Ans:  = Cancel or postpone the punishment of someone",
					"908.Ans:  = An act or instance of waiving a right or claim, rejection",
					"909.Ans:  = Causing harm or damage, detrimental  ",
					"910.Ans:  = Regard or consider in a specified way",
					"911.Ans:  = Dissatisfaction with one's circumstances lack ofcontentment ",
					"912.Ans:  = Declare one's public approval or support of",
					"913.Ans:  = Having many different aspects or features",
					"914.Ans:  = A person or thing causing inconvenience or annoyance ",
					"915.Ans:  = Difficult to find, catch, or achieve",
					"916.Ans:  = Having or showing a strong wish to take things for yourself   ",
					"917.Ans:  = Great destruction or damage ",
					"918.Ans:  = Provide with a quality, ability, or asset ",
					"919.Ans:  = Extremely serious or urgent ",
					"920.Ans:  = Severely critical, devastating  ",
									
					"Thanx For joining..."
					)


					#end...
					
					
					
					
					
					



